### PR TITLE
Added an exception handler around the test runner, but still print th…

### PR DESCRIPTION
**Pull request by simplect**
Added an exception handler around the test runner, but still print the error. Also print a user-friendly explaination of what might have gone wrong.

This solves the problem of students having cryptic tracebacks. They are cryptic because the test script fails, usually when calling a non-existing function, or a type-error. Because the traceback includes code from the wincpy check, it looks as if wincpy is bugged/broken, but actually the user did something wrong.

Possible improvements:
- Command-line option to print the whole traceback, this can be usefull if the problem is actually in the test, and we need a bug report from a user.
- Option to print the whole traceback in case of testing the test runners.

### CODE REVIEW

**Comment by simplect** [comment]
While reading a different test I came across the usage of exec_assignment_code(). This seems to use a different approach to the same problem. But some tests, for example the for assignment (c545bc87620d4ced81cbddb8a90b4a51), does not use this safe function.

**Comment by simplect** [comment]
See my issue as well :)

**Review by stfwn — COMMENTED** [review]
Nice suggestion! This is a good spot to capture some exceptions.

I have an approach cooking inspired by pytest, where checks will be split out into functions starting with `check_` and making use of assertions. Any exceptions (assertion errors, but also attribute errors and such) will be caught and added to the results list. This allows students to iteratively write code and check their work with running into attribute errors.

**Comment by simplect** [comment]
Oh it's already merged! I was still considering what to do. Also I just noticed that my commit includes Black formatting, so it's a bit of a dirty diff. Should I fix that? And maybe roll-back?

**Pull request merged**
